/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LaboratoryAutomationSystem;

import CorePackage.Doctor;
import CorePackage.MedicalAnalysis;
import CorePackage.Patient;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bayra
 */
public class ResultShowingForDoctor extends javax.swing.JFrame {

    DefaultTableModel analysisTableModel = new DefaultTableModel();
    String[] columnNames = {"Analysis", "Result", "Doctor Name"};
    Doctor doctorAcc;

    public ResultShowingForDoctor(Doctor doctorAcc) {
        initComponents();
        this.doctorAcc = doctorAcc;
        for (Patient myPatient : doctorAcc.getMyPatients()) {
            for (MedicalAnalysis myMedicalAnalysis : myPatient.getMyMedicalAnalysis()) {
                analysisComboBox.addItem(myMedicalAnalysis);

            }

        }
        analysisTableModel.setColumnIdentifiers(columnNames);
        analysisTable.setModel(analysisTableModel);
        setLocationRelativeTo(null);
        refreshTable();
    }

    public void refreshTable() {
        analysisTableModel.setRowCount(0);
        MedicalAnalysis selectedMedicalAnalysis = (MedicalAnalysis) analysisComboBox.getSelectedItem();
        for (int i = 0; i < selectedMedicalAnalysis.getResult().length; i++) {
            if (selectedMedicalAnalysis.getMedicalAnalysisType().equals(MedicalAnalysis.analysisType[0])) {
                Vector vector = new Vector();
                vector.add(MedicalAnalysis.bloodExaminations[i]);
                vector.add(selectedMedicalAnalysis.getResult()[i]);
                vector.add(selectedMedicalAnalysis.getDoctor());
                analysisTableModel.addRow(vector);

            } else {
                Vector vector = new Vector();
                vector.add(MedicalAnalysis.urineExaminations[i]);
                vector.add(selectedMedicalAnalysis.getResult()[i]);
                vector.add(selectedMedicalAnalysis.getDoctor());
                analysisTableModel.addRow(vector);

            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        analysisTable = new javax.swing.JTable();
        analysisComboBox = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 530));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setBackground(new java.awt.Color(51, 153, 255));
        headerLabel.setFont(new java.awt.Font("Segoe UI Light", 3, 48)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("RESULT SCREEN");
        headerLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 690, 70));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(51, 153, 255));
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        analysisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Analysis", "Result", "Doctor Name"
            }
        ));
        jScrollPane2.setViewportView(analysisTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 730, 350));

        analysisComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analysisComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(analysisComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 220, 40));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 210, 40));

        findButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        findButton.setText("Find");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });
        jPanel2.add(findButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 80, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if ((JOptionPane.showConfirmDialog(this, "Do You Want To Go Back?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)) {
            DoctorControlPage doctorControlPage = new DoctorControlPage(doctorAcc);
            doctorControlPage.show();
            dispose();
        } else {

        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void analysisComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysisComboBoxActionPerformed
        refreshTable();
    }//GEN-LAST:event_analysisComboBoxActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        Pattern pattern = Pattern.compile(jTextField1.getText());
        for (Patient myPatient : doctorAcc.getMyPatients()) {
            for (MedicalAnalysis myMedicalAnalysis : myPatient.getMyMedicalAnalysis()) {
                
                Matcher matcher = pattern.matcher(myMedicalAnalysis.getPatient().toString());
                if(matcher.find()){
                    
                    analysisComboBox.setSelectedItem(myMedicalAnalysis);
                    refreshTable();
                }

            }

        }
        
    }//GEN-LAST:event_findButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultShowingForDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultShowingForDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultShowingForDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultShowingForDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new ResultShowingForDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> analysisComboBox;
    private javax.swing.JTable analysisTable;
    private javax.swing.JButton backButton;
    private javax.swing.JButton findButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
